export const SEED_CAFES = [
  {
    name: 'Anomali Coffee Menteng',
    address: 'Jl. Teuku Cik Ditiro No.52, RT.10/RW.5, Menteng, Kec. Menteng, Kota Jakarta Pusat',
    latitude: -6.1958,
    longitude: 106.8346,
    rating: 4.6,
    total_reviews: 1250,
    price_level: '$$',
    phone: '+62-21-3101456',
    description: 'Cabang Anomali Menteng dengan suasana homey dan menyajikan berbagai kopi asli Indonesia.',
    amenities: { wifi: true, parking: true, outdoor_seating: true, power_outlets: true, meeting_room: true, pet_friendly: false },
    cuisine_type: ['coffee', 'pastry', 'indonesian'],
    area_slug: 'jakarta-pusat',
    thumbnail: 'https://images.unsplash.com/photo-1559496417-e7f25cb247f3?w=600&h=400&fit=crop',
    source: 'seed'
  },
  {
    name: 'Toko Kopi Tuku Cipete',
    address: 'Jl. Cipete Raya No.7, RT.6/RW.3, Cipete Sel., Kec. Cilandak, Kota Jakarta Selatan',
    latitude: -6.2626,
    longitude: 106.7980,
    rating: 4.8,
    total_reviews: 3200,
    price_level: '$',
    phone: '+62-811-1234567',
    description: 'Pelopor Kopi Susu Tetangga yang legendaris, selalu ramai dengan antrean gojek maupun pengunjung.',
    amenities: { wifi: false, parking: false, outdoor_seating: true, power_outlets: false, meeting_room: false, pet_friendly: true },
    cuisine_type: ['coffee', 'snack'],
    area_slug: 'jakarta-selatan',
    thumbnail: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&h=400&fit=crop',
    source: 'seed'
  },
  {
    name: 'Giyanti Coffee Roastery',
    address: 'Jl. Surabaya No.20, RT.15/RW.5, Menteng, Kec. Menteng, Kota Jakarta Pusat',
    latitude: -6.2023,
    longitude: 106.8402,
    rating: 4.7,
    total_reviews: 1850,
    price_level: '$$$',
    phone: '+62-21-31923698',
    description: 'Salah satu roastery terbaik di Jakarta dengan biji kopi pilihan dan suasana estetik ala Bali.',
    amenities: { wifi: false, parking: true, outdoor_seating: true, power_outlets: false, meeting_room: false, pet_friendly: false },
    cuisine_type: ['coffee', 'pastry', 'dessert'],
    area_slug: 'jakarta-pusat',
    thumbnail: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&h=400&fit=crop',
    source: 'seed'
  },
  {
    name: 'One Fifteenth Coffee',
    address: 'Jl. Gandaria 1 No.63, RT.2/RW.3, Kramat Pela, Kec. Kby. Baru, Kota Jakarta Selatan',
    latitude: -6.2425,
    longitude: 106.7951,
    rating: 4.6,
    total_reviews: 1420,
    price_level: '$$$',
    phone: '+62-21-7225678',
    description: 'Spesialis kopi dengan hidangan brunch yang lezat dan interior modern minimalis.',
    amenities: { wifi: true, parking: true, outdoor_seating: false, power_outlets: true, meeting_room: true, pet_friendly: false },
    cuisine_type: ['coffee', 'brunch', 'western'],
    area_slug: 'jakarta-selatan',
    thumbnail: 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=600&h=400&fit=crop',
    source: 'seed'
  },
  {
    name: '% Arabica Jakarta Roastery',
    address: 'Senopati, Kec. Kby. Baru, Kota Jakarta Selatan',
    latitude: -6.2301,
    longitude: 106.8066,
    rating: 4.5,
    total_reviews: 950,
    price_level: '$$$',
    phone: '+62-21-12345678',
    description: 'Brand kopi terkenal dari Kyoto, Jepang, dengan desain toko putih bersih yang ikonis.',
    amenities: { wifi: true, parking: true, outdoor_seating: true, power_outlets: true, meeting_room: false, pet_friendly: false },
    cuisine_type: ['coffee', 'pastry'],
    area_slug: 'jakarta-selatan',
    thumbnail: 'https://images.unsplash.com/photo-1521017432531-fde3a5004131?w=600&h=400&fit=crop',
    source: 'seed'
  },
  {
    name: 'Common Grounds Neo Soho',
    address: 'Neo Soho Mall, Letjen S. Parman, Tanjung Duren Sel., Kec. Grogol petamburan, Kota Jakarta Barat',
    latitude: -6.1754,
    longitude: 106.7901,
    rating: 4.6,
    total_reviews: 780,
    price_level: '$$$',
    phone: '+62-21-27893333',
    description: 'Tempat favorit untuk brunch dan ngopi sambil jalan-jalan di mall.',
    amenities: { wifi: true, parking: true, outdoor_seating: false, power_outlets: true, meeting_room: false, pet_friendly: false },
    cuisine_type: ['coffee', 'brunch'],
    area_slug: 'jakarta-barat',
    thumbnail: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=400&fit=crop',
    source: 'seed'
  },
  {
    name: 'Kopi Kenangan - Kota Tua',
    address: 'Kawasan Kota Tua, Pinangsia, Taman Sari, Kota Jakarta Barat',
    latitude: -6.1363,
    longitude: 106.8130,
    rating: 4.4,
    total_reviews: 650,
    price_level: '$',
    phone: '+62-21-6921234',
    description: 'Kopi Kenangan dengan nuansa bangunan bersejarah di Kota Tua Jakarta.',
    amenities: { wifi: true, parking: false, outdoor_seating: true, power_outlets: true, meeting_room: false, pet_friendly: false },
    cuisine_type: ['coffee', 'bread'],
    area_slug: 'jakarta-barat',
    thumbnail: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&h=400&fit=crop',
    source: 'seed'
  },
  {
    name: 'Fore Coffee - Kelapa Gading',
    address: 'Jl. Boulevard Raya, Kelapa Gading Timur, Kec. Klp. Gading, Kota Jakarta Utara',
    latitude: -6.1601,
    longitude: 106.9056,
    rating: 4.5,
    total_reviews: 820,
    price_level: '$$',
    phone: '+62-21-4501234',
    description: 'Kopi modern dengan berbagai pilihan minuman dingin yang menyegarkan.',
    amenities: { wifi: true, parking: true, outdoor_seating: true, power_outlets: true, meeting_room: false, pet_friendly: false },
    cuisine_type: ['coffee', 'pastry'],
    area_slug: 'jakarta-utara',
    thumbnail: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=600&h=400&fit=crop',
    source: 'seed'
  },
  {
    name: 'Ombe Kofie Pluit',
    address: 'Pluit Karang Utara No.119, Pluit, Penjaringan, Kota Jakarta Utara',
    latitude: -6.1132,
    longitude: 106.7891,
    rating: 4.7,
    total_reviews: 540,
    price_level: '$$$',
    phone: '+62-21-6691234',
    description: 'Kopi premium dengan pelayanan ramah dan suasana yang sangat homey.',
    amenities: { wifi: true, parking: true, outdoor_seating: false, power_outlets: true, meeting_room: false, pet_friendly: false },
    cuisine_type: ['coffee', 'dessert'],
    area_slug: 'jakarta-utara',
    thumbnail: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=600&h=400&fit=crop',
    source: 'seed'
  },
  {
    name: 'Tanamera Coffee Rawamangun',
    address: 'Jl. Pemuda No. 18, Rawamangun, Pulo Gadung, Kota Jakarta Timur',
    latitude: -6.1951,
    longitude: 106.8845,
    rating: 4.6,
    total_reviews: 1100,
    price_level: '$$',
    phone: '+62-21-4751234',
    description: 'Sajian kopi Nusantara yang dipanggang sendiri, cocok untuk kerja santai.',
    amenities: { wifi: true, parking: true, outdoor_seating: true, power_outlets: true, meeting_room: true, pet_friendly: false },
    cuisine_type: ['coffee', 'western', 'indonesian'],
    area_slug: 'jakarta-timur',
    thumbnail: 'https://images.unsplash.com/photo-1493857671505-72967e2e2760?w=600&h=400&fit=crop',
    source: 'seed'
  }
];
